#!/usr/bin/env bash
# Makes sure:
#+ nginx is running as user nginx
#+ nginx must be listening on all active IP on port 8080
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
